#!/bin/bash

# Zotero Plugin Release and Publish Script
# Creates releases, generates changelogs, and publishes to GitHub

set -e

PLUGINS_DIR="/home/zotero-plugins"
PLUGINS=("zotero-metadata-plugin" "zotero-jisedigi-api" "zotero-vercel-ocr")
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
RELEASE_LOG="/tmp/zotero-release-${TIMESTAMP}.log"
RELEASE_DIR="/home/releases"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1" | tee -a "$RELEASE_LOG"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1" | tee -a "$RELEASE_LOG"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$RELEASE_LOG"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a "$RELEASE_LOG"
}

# Generate changelog
generate_changelog() {
    local plugin=$1
    local plugin_path="$PLUGINS_DIR/$plugin"
    local changelog_file="$plugin_path/CHANGELOG.md"
    
    log_info "Generating changelog for $plugin..."
    
    cd "$plugin_path"
    
    # Get version
    local version=$(grep '"version"' package.json | head -1 | sed 's/.*"version": "\([^"]*\)".*/\1/')
    
    # Get recent commits
    local commits=$(git log --oneline -10 2>/dev/null || echo "No commits found")
    
    # Create or update changelog
    if [ -f "$changelog_file" ]; then
        # Prepend new entry
        {
            echo "## [$version] - $(date +%Y-%m-%d)"
            echo ""
            echo "### Changes"
            echo "$commits" | sed 's/^/- /'
            echo ""
            cat "$changelog_file"
        } > "$changelog_file.tmp"
        mv "$changelog_file.tmp" "$changelog_file"
    else
        # Create new changelog
        cat > "$changelog_file" <<EOF
# Changelog

All notable changes to this project will be documented in this file.

## [$version] - $(date +%Y-%m-%d)

### Changes
$commits

EOF
    fi
    
    log_success "Changelog generated for $plugin"
}

# Create release notes
create_release_notes() {
    local plugin=$1
    local plugin_path="$PLUGINS_DIR/$plugin"
    local version=$(grep '"version"' package.json | head -1 | sed 's/.*"version": "\([^"]*\)".*/\1/')
    local release_notes_file="$RELEASE_DIR/${plugin}-v${version}-release-notes.md"
    
    log_info "Creating release notes for $plugin v$version..."
    
    cd "$plugin_path"
    
    cat > "$release_notes_file" <<EOF
# Release Notes: $plugin v$version

**Release Date:** $(date +%Y-%m-%d)

## Overview
This release includes bug fixes, optimizations, and new features.

## What's New
- Automated build and optimization pipeline
- Enhanced error handling
- Improved code quality
- Updated dependencies

## Build Information
- Build Timestamp: $TIMESTAMP
- Node Version: $(node --version)
- NPM Version: $(npm --version)

## Installation
1. Download the .xpi file from the releases page
2. Open Zotero
3. Go to Tools → Add-ons
4. Click the gear icon and select "Install Add-on From File"
5. Select the downloaded .xpi file

## Bug Fixes & Improvements
EOF
    
    # Add recent commits
    git log --oneline -5 2>/dev/null | sed 's/^/- /' >> "$release_notes_file" || echo "- Automated build and release" >> "$release_notes_file"
    
    cat >> "$release_notes_file" <<EOF

## Known Issues
None reported at this time.

## Support
For issues or questions, please visit: https://github.com/hellonetizens/$plugin

---
Generated by Automated Release Pipeline
EOF
    
    log_success "Release notes created: $release_notes_file"
}

# Update version in package.json
update_version() {
    local plugin=$1
    local plugin_path="$PLUGINS_DIR/$plugin"
    
    log_info "Checking version for $plugin..."
    
    cd "$plugin_path"
    
    # Get current version
    local current_version=$(grep '"version"' package.json | head -1 | sed 's/.*"version": "\([^"]*\)".*/\1/')
    
    # Parse version components
    local major=$(echo "$current_version" | cut -d. -f1)
    local minor=$(echo "$current_version" | cut -d. -f2)
    local patch=$(echo "$current_version" | cut -d. -f3)
    
    # Increment patch version
    local new_patch=$((patch + 1))
    local new_version="$major.$minor.$new_patch"
    
    log_info "Current version: $current_version"
    log_info "New version: $new_version"
    
    # Update package.json
    sed -i "s/\"version\": \"$current_version\"/\"version\": \"$new_version\"/" package.json
    
    log_success "Version updated to $new_version"
}

# Commit release changes
commit_release() {
    local plugin=$1
    local plugin_path="$PLUGINS_DIR/$plugin"
    
    log_info "Committing release changes for $plugin..."
    
    cd "$plugin_path"
    
    # Stage changes
    git add -A
    
    # Get version
    local version=$(grep '"version"' package.json | head -1 | sed 's/.*"version": "\([^"]*\)".*/\1/')
    
    # Commit
    git commit -m "Release: v$version - $TIMESTAMP" 2>&1 | tee -a "$RELEASE_LOG" || log_warning "No changes to commit"
    
    # Push
    log_info "Pushing release commit..."
    git push 2>&1 | tee -a "$RELEASE_LOG" || log_warning "Failed to push"
    
    log_success "Release committed for $plugin"
}

# Create GitHub release tag
create_release_tag() {
    local plugin=$1
    local plugin_path="$PLUGINS_DIR/$plugin"
    
    log_info "Creating release tag for $plugin..."
    
    cd "$plugin_path"
    
    # Get version
    local version=$(grep '"version"' package.json | head -1 | sed 's/.*"version": "\([^"]*\)".*/\1/')
    local tag="v$version"
    
    # Create annotated tag
    git tag -a "$tag" -m "Release: $plugin v$version - $TIMESTAMP" 2>&1 | tee -a "$RELEASE_LOG" || log_warning "Tag already exists"
    
    # Push tag
    log_info "Pushing tag to remote..."
    git push origin "$tag" 2>&1 | tee -a "$RELEASE_LOG" || log_warning "Failed to push tag"
    
    log_success "Release tag created: $tag"
}

# Create GitHub release via API
create_github_release_api() {
    local plugin=$1
    local plugin_path="$PLUGINS_DIR/$plugin"
    local api_token="$2"
    
    if [ -z "$api_token" ]; then
        log_warning "GitHub API token not provided, skipping API release creation"
        return 0
    fi
    
    log_info "Creating GitHub release via API for $plugin..."
    
    cd "$plugin_path"
    
    # Get version
    local version=$(grep '"version"' package.json | head -1 | sed 's/.*"version": "\([^"]*\)".*/\1/')
    local tag="v$version"
    
    # Get repository info
    local repo_url=$(git config --get remote.origin.url | sed 's/.*github.com[:/]\(.*\)\.git/\1/')
    
    # Find XPI file
    local xpi_file=$(find "$RELEASE_DIR" -name "${plugin}*.xpi" -type f | head -1)
    
    if [ -z "$xpi_file" ]; then
        log_warning "No XPI file found for $plugin"
        return 1
    fi
    
    # Create release JSON
    local release_json=$(cat <<EOF
{
  "tag_name": "$tag",
  "name": "$plugin v$version",
  "body": "Automated release - $TIMESTAMP",
  "draft": false,
  "prerelease": false
}
EOF
)
    
    # Create release via API
    log_info "Uploading release to GitHub..."
    curl -X POST \
        -H "Authorization: token $api_token" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/$repo_url/releases" \
        -d "$release_json" 2>&1 | tee -a "$RELEASE_LOG" || log_warning "Failed to create release via API"
    
    log_success "GitHub release created via API"
}

# Generate release summary
generate_release_summary() {
    local summary_file="$RELEASE_DIR/release-summary-${TIMESTAMP}.md"
    
    log_info "Generating release summary..."
    
    cat > "$summary_file" <<EOF
# Zotero Plugin Release Summary
**Release Date:** $(date +%Y-%m-%d\ %H:%M:%S)

## Released Plugins
EOF
    
    for plugin in "${PLUGINS[@]}"; do
        plugin_path="$PLUGINS_DIR/$plugin"
        if [ -d "$plugin_path" ]; then
            cd "$plugin_path"
            
            version=$(grep '"version"' package.json | head -1 | sed 's/.*"version": "\([^"]*\)".*/\1/')
            
            echo "" >> "$summary_file"
            echo "### $plugin" >> "$summary_file"
            echo "- Version: v$version" >> "$summary_file"
            echo "- Tag: v$version" >> "$summary_file"
            
            # Find XPI file
            xpi_file=$(find "$RELEASE_DIR" -name "${plugin}*.xpi" -type f | head -1)
            if [ -n "$xpi_file" ]; then
                xpi_size=$(du -h "$xpi_file" | cut -f1)
                echo "- XPI File: $(basename "$xpi_file") ($xpi_size)" >> "$summary_file"
            fi
        fi
    done
    
    echo "" >> "$summary_file"
    echo "## Release Artifacts" >> "$summary_file"
    echo "" >> "$summary_file"
    
    # List all release files
    ls -lh "$RELEASE_DIR" | grep -E "\.(xpi|md|json)$" | awk '{print "- " $9 " (" $5 ")"}' >> "$summary_file"
    
    log_success "Release summary generated: $summary_file"
}

# Main execution
main() {
    echo "=== Zotero Plugin Release Pipeline ===" | tee "$RELEASE_LOG"
    echo "Timestamp: $TIMESTAMP" | tee -a "$RELEASE_LOG"
    echo "" | tee -a "$RELEASE_LOG"
    
    # Get API token if provided
    API_TOKEN="${1:-}"
    
    for plugin in "${PLUGINS[@]}"; do
        log_info "Processing release for $plugin..." | tee -a "$RELEASE_LOG"
        
        # Generate changelog
        generate_changelog "$plugin"
        echo "" | tee -a "$RELEASE_LOG"
        
        # Create release notes
        create_release_notes "$plugin"
        echo "" | tee -a "$RELEASE_LOG"
        
        # Update version
        update_version "$plugin"
        echo "" | tee -a "$RELEASE_LOG"
        
        # Commit release
        commit_release "$plugin"
        echo "" | tee -a "$RELEASE_LOG"
        
        # Create tag
        create_release_tag "$plugin"
        echo "" | tee -a "$RELEASE_LOG"
        
        # Create GitHub release via API if token provided
        if [ -n "$API_TOKEN" ]; then
            create_github_release_api "$plugin" "$API_TOKEN"
            echo "" | tee -a "$RELEASE_LOG"
        fi
    done
    
    # Generate summary
    generate_release_summary
    
    log_success "Release pipeline complete"
    log_info "Release log: $RELEASE_LOG"
    log_info "Release directory: $RELEASE_DIR"
}

# Run main
main "$@"
